# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'kaspersky_security_center_analisys.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(644, 621)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setStyleSheet("background-color: rgb(85, 170, 127);")
        self.centralwidget.setObjectName("centralwidget")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(-100, -20, 971, 151))
        self.frame.setStyleSheet("background-color: rgb(58, 117, 87);\n"
"")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.label = QtWidgets.QLabel(self.frame)
        self.label.setGeometry(QtCore.QRect(130, 30, 541, 61))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(20)
        self.label.setFont(font)
        self.label.setStyleSheet("color: rgb(255, 255, 255);")
        self.label.setObjectName("label")
        self.input_ip_address = QtWidgets.QLineEdit(self.centralwidget)
        self.input_ip_address.setGeometry(QtCore.QRect(40, 160, 241, 41))
        self.input_ip_address.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border: 3px solid rgb(78, 156, 116);\n"
"border-radius: 15;\n"
"color: rgb(0, 0, 0);")
        self.input_ip_address.setInputMask("")
        self.input_ip_address.setAlignment(QtCore.Qt.AlignCenter)
        self.input_ip_address.setObjectName("input_ip_address")
        self.input_fileaddress = QtWidgets.QLineEdit(self.centralwidget)
        self.input_fileaddress.setGeometry(QtCore.QRect(40, 310, 241, 41))
        self.input_fileaddress.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border: 3px solid rgb(78, 156, 116);\n"
"border-radius: 15;\n"
"color: rgb(0, 0, 0);")
        self.input_fileaddress.setInputMask("")
        self.input_fileaddress.setAlignment(QtCore.Qt.AlignCenter)
        self.input_fileaddress.setObjectName("input_fileaddress")
        self.input_login = QtWidgets.QLineEdit(self.centralwidget)
        self.input_login.setGeometry(QtCore.QRect(40, 410, 241, 41))
        self.input_login.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border: 3px solid rgb(78, 156, 116);\n"
"border-radius: 15;\n"
"color: rgb(0, 0, 0);")
        self.input_login.setInputMask("")
        self.input_login.setAlignment(QtCore.Qt.AlignCenter)
        self.input_login.setObjectName("input_login")
        self.input_password = QtWidgets.QLineEdit(self.centralwidget)
        self.input_password.setGeometry(QtCore.QRect(40, 460, 241, 41))
        self.input_password.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border: 3px solid rgb(78, 156, 116);\n"
"border-radius: 15;\n"
"color: rgb(0, 0, 0);")
        self.input_password.setInputMask("")
        self.input_password.setAlignment(QtCore.Qt.AlignCenter)
        self.input_password.setObjectName("input_password")
        self.enter_ip_address = QtWidgets.QPushButton(self.centralwidget)
        self.enter_ip_address.setGeometry(QtCore.QRect(40, 210, 241, 41))
        self.enter_ip_address.setStyleSheet("QPushButton {\n"
"    color: rgb(255, 255, 255);\n"
"    background-color: rgb(69, 138, 102);\n"
"    border-radius : 15;\n"
"}\n"
"\n"
"QPushButton: pressed {\n"
"    color: rgb(255, 255, 255);\n"
"    background-color: rgb(55, 111, 82);\n"
"    border-radius : 15;\n"
"}")
        self.enter_ip_address.setObjectName("enter_ip_address")
        self.enter_fileaddress = QtWidgets.QPushButton(self.centralwidget)
        self.enter_fileaddress.setGeometry(QtCore.QRect(40, 360, 241, 41))
        self.enter_fileaddress.setStyleSheet("QPushButton {\n"
"    color: rgb(255, 255, 255);\n"
"    background-color: rgb(69, 138, 102);\n"
"    border-radius : 15;\n"
"}\n"
"\n"
"QPushButton: pressed {\n"
"    color: rgb(255, 255, 255);\n"
"    background-color: rgb(55, 111, 82);\n"
"    border-radius : 15;\n"
"}")
        self.enter_fileaddress.setObjectName("enter_fileaddress")
        self.ente_autorization_DIB = QtWidgets.QPushButton(self.centralwidget)
        self.ente_autorization_DIB.setGeometry(QtCore.QRect(40, 510, 241, 41))
        self.ente_autorization_DIB.setStyleSheet("QPushButton {\n"
"    color: rgb(255, 255, 255);\n"
"    background-color: rgb(69, 138, 102);\n"
"    border-radius : 15;\n"
"}\n"
"\n"
"QPushButton: pressed {\n"
"    color: rgb(255, 255, 255);\n"
"    background-color: rgb(55, 111, 82);\n"
"    border-radius : 15;\n"
"}")
        self.ente_autorization_DIB.setObjectName("ente_autorization_DIB")
        self.ente_autorization_DIB_2 = QtWidgets.QPushButton(self.centralwidget)
        self.ente_autorization_DIB_2.setGeometry(QtCore.QRect(40, 560, 241, 41))
        self.ente_autorization_DIB_2.setStyleSheet("QPushButton {\n"
"    color: rgb(255, 255, 255);\n"
"    background-color: rgb(69, 138, 102);\n"
"    border-radius : 15;\n"
"}\n"
"\n"
"QPushButton: pressed {\n"
"    color: rgb(255, 255, 255);\n"
"    background-color: rgb(55, 111, 82);\n"
"    border-radius : 15;\n"
"}")
        self.ente_autorization_DIB_2.setObjectName("ente_autorization_DIB_2")
        self.download_policies = QtWidgets.QPushButton(self.centralwidget)
        self.download_policies.setGeometry(QtCore.QRect(350, 160, 251, 41))
        self.download_policies.setStyleSheet("QPushButton {\n"
"    color: rgb(255, 255, 255);\n"
"    background-color: rgb(69, 138, 102);\n"
"    border-radius : 15;\n"
"}\n"
"\n"
"QPushButton: pressed {\n"
"    color: rgb(255, 255, 255);\n"
"    background-color: rgb(55, 111, 82);\n"
"    border-radius : 15;\n"
"}")
        self.download_policies.setObjectName("download_policies")
        self.download_tasks = QtWidgets.QPushButton(self.centralwidget)
        self.download_tasks.setGeometry(QtCore.QRect(350, 210, 251, 41))
        self.download_tasks.setStyleSheet("QPushButton {\n"
"    color: rgb(255, 255, 255);\n"
"    background-color: rgb(69, 138, 102);\n"
"    border-radius : 15;\n"
"}\n"
"\n"
"QPushButton: pressed {\n"
"    color: rgb(255, 255, 255);\n"
"    background-color: rgb(55, 111, 82);\n"
"    border-radius : 15;\n"
"}")
        self.download_tasks.setObjectName("download_tasks")
        self.download_policies_from_file = QtWidgets.QPushButton(self.centralwidget)
        self.download_policies_from_file.setGeometry(QtCore.QRect(350, 260, 251, 41))
        self.download_policies_from_file.setStyleSheet("QPushButton {\n"
"    color: rgb(255, 255, 255);\n"
"    background-color: rgb(69, 138, 102);\n"
"    border-radius : 15;\n"
"}\n"
"\n"
"QPushButton: pressed {\n"
"    color: rgb(255, 255, 255);\n"
"    background-color: rgb(55, 111, 82);\n"
"    border-radius : 15;\n"
"}")
        self.download_policies_from_file.setObjectName("download_policies_from_file")
        self.download_tasks_from_file = QtWidgets.QPushButton(self.centralwidget)
        self.download_tasks_from_file.setGeometry(QtCore.QRect(350, 310, 251, 41))
        self.download_tasks_from_file.setStyleSheet("QPushButton {\n"
"    color: rgb(255, 255, 255);\n"
"    background-color: rgb(69, 138, 102);\n"
"    border-radius : 15;\n"
"}\n"
"\n"
"QPushButton: pressed {\n"
"    color: rgb(255, 255, 255);\n"
"    background-color: rgb(55, 111, 82);\n"
"    border-radius : 15;\n"
"}")
        self.download_tasks_from_file.setObjectName("download_tasks_from_file")
        self.dowload_profiles_from_file = QtWidgets.QPushButton(self.centralwidget)
        self.dowload_profiles_from_file.setGeometry(QtCore.QRect(350, 360, 251, 41))
        self.dowload_profiles_from_file.setStyleSheet("QPushButton {\n"
"    color: rgb(255, 255, 255);\n"
"    background-color: rgb(69, 138, 102);\n"
"    border-radius : 15;\n"
"}\n"
"\n"
"QPushButton: pressed {\n"
"    color: rgb(255, 255, 255);\n"
"    background-color: rgb(55, 111, 82);\n"
"    border-radius : 15;\n"
"}")
        self.dowload_profiles_from_file.setObjectName("dowload_profiles_from_file")
        self.run_script_for_tasks = QtWidgets.QPushButton(self.centralwidget)
        self.run_script_for_tasks.setGeometry(QtCore.QRect(350, 510, 251, 41))
        self.run_script_for_tasks.setStyleSheet("QPushButton {\n"
"    color: rgb(255, 255, 255);\n"
"    background-color: rgb(69, 138, 102);\n"
"    border-radius : 15;\n"
"}\n"
"\n"
"QPushButton: pressed {\n"
"    color: rgb(255, 255, 255);\n"
"    background-color: rgb(55, 111, 82);\n"
"    border-radius : 15;\n"
"}")
        self.run_script_for_tasks.setObjectName("run_script_for_tasks")
        self.run_script_for_policies = QtWidgets.QPushButton(self.centralwidget)
        self.run_script_for_policies.setGeometry(QtCore.QRect(350, 460, 251, 41))
        self.run_script_for_policies.setStyleSheet("QPushButton {\n"
"    color: rgb(255, 255, 255);\n"
"    background-color: rgb(69, 138, 102);\n"
"    border-radius : 15;\n"
"}\n"
"\n"
"QPushButton: pressed {\n"
"    color: rgb(255, 255, 255);\n"
"    background-color: rgb(55, 111, 82);\n"
"    border-radius : 15;\n"
"}")
        self.run_script_for_policies.setObjectName("run_script_for_policies")
        self.dowload_settings_from_file = QtWidgets.QPushButton(self.centralwidget)
        self.dowload_settings_from_file.setGeometry(QtCore.QRect(350, 410, 251, 41))
        self.dowload_settings_from_file.setStyleSheet("QPushButton {\n"
"    color: rgb(255, 255, 255);\n"
"    background-color: rgb(69, 138, 102);\n"
"    border-radius : 15;\n"
"}\n"
"\n"
"QPushButton: pressed {\n"
"    color: rgb(255, 255, 255);\n"
"    background-color: rgb(55, 111, 82);\n"
"    border-radius : 15;\n"
"}")
        self.dowload_settings_from_file.setObjectName("dowload_settings_from_file")
        self.run_scripts_for_profiles = QtWidgets.QPushButton(self.centralwidget)
        self.run_scripts_for_profiles.setGeometry(QtCore.QRect(350, 560, 251, 41))
        self.run_scripts_for_profiles.setStyleSheet("QPushButton {\n"
"    color: rgb(255, 255, 255);\n"
"    background-color: rgb(69, 138, 102);\n"
"    border-radius : 15;\n"
"}\n"
"\n"
"QPushButton: pressed {\n"
"    color: rgb(255, 255, 255);\n"
"    background-color: rgb(55, 111, 82);\n"
"    border-radius : 15;\n"
"}")
        self.run_scripts_for_profiles.setObjectName("run_scripts_for_profiles")
        self.enter_ip_address_2 = QtWidgets.QPushButton(self.centralwidget)
        self.enter_ip_address_2.setGeometry(QtCore.QRect(40, 260, 241, 41))
        self.enter_ip_address_2.setStyleSheet("QPushButton {\n"
"    color: rgb(255, 255, 255);\n"
"    background-color: rgb(69, 138, 102);\n"
"    border-radius : 15;\n"
"}\n"
"\n"
"QPushButton: pressed {\n"
"    color: rgb(255, 255, 255);\n"
"    background-color: rgb(55, 111, 82);\n"
"    border-radius : 15;\n"
"}")
        self.enter_ip_address_2.setObjectName("enter_ip_address_2")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Kaspersky Security Center Analyzer"))
        self.label.setText(_translate("MainWindow", "Kaspersky Security Center Analyzer"))
        self.input_ip_address.setText(_translate("MainWindow", "Введите IP-адрес сервера"))
        self.input_fileaddress.setText(_translate("MainWindow", "Введите адрес для сохранения"))
        self.input_login.setText(_translate("MainWindow", "Введите ЛОГИН"))
        self.input_password.setText(_translate("MainWindow", "Введите ПАРОЛЬ"))
        self.enter_ip_address.setText(_translate("MainWindow", "Подключиться к серверу"))
        self.enter_fileaddress.setText(_translate("MainWindow", "Ввод"))
        self.ente_autorization_DIB.setText(_translate("MainWindow", "Авторизоваться-DIB"))
        self.ente_autorization_DIB_2.setText(_translate("MainWindow", "Авторизоваться-RNKO"))
        self.download_policies.setText(_translate("MainWindow", "Собрать данные из раздела \"Политики\""))
        self.download_tasks.setText(_translate("MainWindow", "Собрать данные из раздела \"Задачи\""))
        self.download_policies_from_file.setText(_translate("MainWindow", "Загрузить словарь политик из файла"))
        self.download_tasks_from_file.setText(_translate("MainWindow", "Загрузить словарь задач из файла"))
        self.dowload_profiles_from_file.setText(_translate("MainWindow", "Загрузить словарь профилей из файла"))
        self.run_script_for_tasks.setText(_translate("MainWindow", "Запуск скрипта для задач"))
        self.run_script_for_policies.setText(_translate("MainWindow", "Запуск скрипта для политик"))
        self.dowload_settings_from_file.setText(_translate("MainWindow", "Загрузить словарь настроек из файла"))
        self.run_scripts_for_profiles.setText(_translate("MainWindow", "Запуск скрипта для профилей"))
        self.enter_ip_address_2.setText(_translate("MainWindow", "Отключиться от сервера"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
